### ISSUE TITLE
midi bends

### ISSUE THREAD

**Issue by rikamusik** [CLeJack/Scribe#7]
hello charles,
first of all, thanks for this project
it works very good on ubuntu 20.04
I was wondering if you ever tried to incorporate midi bends (pitchwheel) into the plugin
where would you try to hook that into the code ?

thanks
rikamusik

**Comment by CLeJack** [comment]
Hi Rikamusik,

I'm glad to hear that it's working well for you! I have thought about pitchbend, and I haven't been able to figure out a good way to do it purely through software without some sort of user input. Long story short, the numbers that I'm using to make decisions will show a lot of similarity when looking at slides, hammer ons, or bends. Without a neural network, I think human input is needed to tell the system "Interpret transitions as [distinct notes / pitch bending]."

Two paths I see are:

1. Get a midi foot pedal with expression pedals. This side steps the problem entirely.
2. Add a pitchBendOn bool and associated state and trigger it with a midi foot switch. This would be you as a user telling the system how to interpret the data.

There would be a few changes that needed to be made to implement option 2. There's no real single point to hook this sort of logic into (also I apologize for the incoming wall of text).

Adding pitch bend would look something like this.

Add the following:
Editor and Processor Changes
- juce::button pitchBendOn to the GUI via GUIMain.h
- juce::slider pitchBendRange to the GUI via GUIMain.h
- add justAudioParameterBool to PluginProcessor.cpp for bendOn
- add justAudioParameterInt to PluginProcessor.cpp for bendRange
- update ScribeAudioProcessorEditor::buttonClicked() and SliderValueChanged() to link the AudioEditor and AudioProcessor
- modify ScribeAudioProcessor::updateParams() to link the AudioProcessor and Scribe's internal Parameters

___
DataModel Changes
- bool            pitchBendOn to DataModels,h AudioParameters
- int               pitchBendRange to DataModels,h AudioParameters
- int               pitchBendValue DataModels.h Calculations
- **update      Calculations::updateSignal** to compute and set Calcuations::pitchBendValue which was added

___
MidiSwitch / State Machine Changes
- int               pitchBendValue to MidiSwitch.h MidiParams
- bool            pitchBendOn to MidiSwitch.h MidiParams
- int               pitchBendValue to MidiSwitch.h SwitchMessage

___

- add a bend state to the MidiState enum in MidiSwitch.h
- a case to handle the bend state inside MidiSwitch.cpp MidiSwitch::update
- an initial condition to switch to the bend state _after_ entering the onState inside MidiSwitch.cpp MidiSwitch::on
- a **new SwitchMessage** function that generates the values for a bend message inside MidiSwitch.h and .cpp at line 79 inside the MidiSwitch Struct.

___

From all of the above, everything that isn't bolded involves only adding a variable, adding a simple condition, assigning a variable, or modifying a return. The bold sections would require some new logic, and the most difficult thing would be converting from the transformed signal to a pitch bend value. I'm already bombarding you with text, so I won't expand on this; but let me know if you'd like me to.

___

Finally, the flow of data is all controlled within the function ScribeAudioProcessor::ready

- updateParams() adds all changes seen in the gui to the AudioParameters DataModel which is used by all internal calculations
- A sequence of calls updates the calculations that rely on the aforementioned parameters
- These calculations are passed to the state machine which produces a different SwitchMessage (i.e. midi message) depending on the active state.
- This all ends with a conditional statement if(message.send){ //pass midi data to juce } Currently at line 300 within the ScribeAudioProcess.cpp file at the time of this response (Latest commit cf9ca3e). A modification would need to be made here so cc messages could be sent in addition to on and off messages.

___

That was a mouthful--anyway let me know what you think. The reason I didn't go through with implementing this at some point was because options 1 and 2 both require a foot controller. At that point, it seems like you might as well use an expression pedal to do pitch bending.

**Comment by rikamusik** [comment]
hello charles, 
I was thinking about doing it like this:
-get the played frequency
-get the frequency of the midi note corresponding
-calculate the frequency of the midi note 1 tone higher
-calculate  int (played note - lower note) * 16384 / (higher note - lower note)

-do not send an arbitary NoteOff in ScribeAudioProcess.cpp

like this, I think it would follow the guitar when we bend the strings

tell me what you think
thanks
rikamusik

**Comment by CLeJack** [comment]
If you want to fully eliminate the current retrigger state behavior and ignore the gui integration, this becomes a lot easier.

At MidiSwitch.cpp MidiSwitch::on you can comment out lines 89 - 100. 

You won't have to touch the note off in ScribeAudioProcess.cpp. When there's nothing to turn off the message just sends midi note 0.

___

I'm expanding for clarity but feel free to inline anything below
```
//In ScribeAudioProcess.cpp you can add the following in ScribeAudioProcess::ready after line 298

int lastPlayedNote = scribe.midiSwitch.notes.current  //returns 0 if no note was played

int currentNoteIndex = scribe.fundamental.index //last note that was detected--but without necessarily triggering an on state

float currentFreq = scribe.frequencies[currentNoteIndex]

int currentNote = getMidiNumbers(currentFreq, scribe.tuning.refFreq) //inline function in DataModels.h
```

Then you can use lastPlayedNote and currentNote in your posted formula to get the pitch bend value, and add it to midiMessages. You should _not_ put this inside the conditional at line 300. That is true only when there is a new note caused by a state change.


With respect to your current formula, let's say you have the notes 1, 2, and 3, and you play note 2, and can bend up and down. Your potential outputs would be [0, 8192, and 16384]. If you're okay with bins this large give it a shot, and let me know how it goes.

In the mean time I'll look into getting all of the gui changes and state machine changes setup--I'll aim for starting next weekend. If your method works, I'll integrate it. But if not, I'll try integrating a method I was thinking about in the past. 

In the worst case scenario, the plumbing would be setup to handle pitch bending easily in the future. Keep me posted on what you do, or if the changes I suggested above don't work out for you.

**Comment by rikamusik** [comment]
thanks charles, I will try it as soon as possible, and will keep you posted about the results

**Comment by rikamusik** [comment]
hello charles,
I tried what you told me, currentFreq holds the frequency of the midi note, but I don't find how to get the real frequency played
example: if I bend my A , currentFreq jumps from 440 to 466.164 when it reaches the next semitone
How can we get the real frequency ?
thanks
rikamusik

**Comment by CLeJack** [comment]
I'll see if I can make a function today that can interpolate between notes. Unfortunately, scribe has no means of directly detecting frequencies inbetween semitones.

**Comment by CLeJack** [comment]
It seems I underestimated the difficulty of implementing this. I made the branch "pitchbend" and I currently have something that seems to be solid, but I haven't tested it live. I'll add it to the VST tomorrow, and see how it plays.

At the moment there's a new function Calculations::updatePitchWheel, and the output can be grabbed from calcs.pitchWheelPosition. The output is in the range [-1,1]
